system/ejournal/urls.py
from django.urls import path, re_path
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from . import views

# Метаданные Swagger
schema_view = get_schema_view(
    openapi.Info(
        title="E-Journal API",
        default_version='v1',
        description="E-Journal API",
        terms_of_service="https://example.com",
        contact=openapi.Contact(email="contact@mail.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # path("admin/", admin.site.urls),
    # # path("", groupList.as_view(), name='groups'),
    # path('groups/', groupList.as_view(), name='groups'),
    # path('teachers/', TeachersList.as_view(), name='teachers'),
    # path('disciplines/', DisciplinesList.as_view(), name='disciplines'),
    # re_path(r'^group/(?P<pk>\d+)$', groupDetailView.as_view(), name="group-detail"),
    # re_path(r'^group-edit/(?P<pk>\d+)$', groupUpdateView.as_view(), name="group-edit"),
    # path('groups/create', groupCreateView.as_view(), name="group-create"),
    # re_path(r'^group-delete/(?P<pk>\d+)$', groupDeleteView.as_view(), name="group-delete"),
    # path('teacher/create', TeacherCreateView.as_view(), name="teacher-create"),
    # re_path(r'^teacher-edit/(?P<pk>\d+)$', TeacherEditView.as_view(), name="teacher-edit"),
    # re_path(r'^teacher-detele/(?P<pk>\d+)$', TeacherDeleteView.as_view(), name="teacher-delete"),
    # re_path(r'^teacher/(?P<pk>\d+)$', TeacherDetailView.as_view(), name="teacher-detail"),
    # path('discipline/create', DisciplineCreateView.as_view(), name="disсipline-create"),
    # re_path(r'^discipline-edit/(?P<pk>\d+)$', DisciplineEditView.as_view(), name="discipline-edit"),
    # re_path(r'^discipline-detele/(?P<pk>\d+)$', DisciplineDeleteView.as_view(), name="discipline-delete"),
    # re_path(r'^discipline/(?P<pk>\d+)$', DisciplineDetailView.as_view(), name="discipline-detail"),
    # path('group/rating/<int:pk>/', rating_log, name='rating'),
    # path('group/group-study-rating/<int:pk>/', group_study_raiting, name='group-study-rating'),
    # path('group/group-visiting-rating/<int:pk>/', group_visiting_raiting, name='group-visiting-rating'),
    # path('group/group-addres-rating/<int:pk>/', group_addres_raiting, name='group-add-res-rating'),
    # path('group/group-total-rating/<int:pk>/', group_total_raiting, name='group-total-rating'),
    # path('', views.LoginView.as_view(), name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('student_stat/', student_stat, name="student_stat"),
    # path('chech_perm/', check_perm, name="check_perm"),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
            name='schema-swagger-ui'),

    path('groups', views.GroupListRest.as_view(), name = 'groups'),
    path('teachers', views.TeacherListRest.as_view(), name='teachers'),
    path('disciplines', views.DisciplineListRest.as_view(), name='disciplines'),
    path('group/create', views.GroupCreateRest.as_view(), name="group-create"),
    path('group/delete/<int:id>', views.GroupDeleteRest.as_view(), name="group-delete"),
    path('group/<int:id>', views.GroupDetailRest.as_view(), name="group-detail"),
    path('group-edit/<int:id>', views.GroupEdit.as_view(), name="group-edit"),
    path('teacher/create', views.TeacherCreateRest.as_view(), name="teacher-create"),
    path('teacher/edit/<int:id>', views.TeacherUpdate.as_view(), name='teacher-edit'),
    path('teacher/delete/<int:id>', views.TeacherDeleteRest.as_view(), name='teacher-delete'),
    path('teacher/<int:id>', views.TeacherDetailRest.as_view(), name="teacher-detail"),
    path('group/edit/<int:id>', views.GroupEdit.as_view(), name="group-edit"),
    path('discipline/create', views.DisciplineCreateRest.as_view(), name="discipline-create"),
    path('discipline/delete/<int:id>', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:id>', views.DisciplineDetail.as_view(), name="discipline-detail"),
    path('group/mark/<int:id>', views.MarkUpdate.as_view()),
    path('docs', views.docs)
    # path('accounts/profile/', student_stat)
]

system/system/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, re_path
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


urlpatterns = [
    path('api/', include('ejournal.urls')),  # подключаем Views из приложения weatherapp
    path('admin/', admin.site.urls),

]

system/ejournal/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.urls import reverse


# модель Студент
class Student(models.Model):
    # surname - фамилия
    surname = models.CharField(max_length=80, verbose_name="фамилия")
    # name - имя
    name = models.CharField(max_length=80, verbose_name='имя')
    # patronymic - отчество
    patronymic = models.CharField(max_length=80, verbose_name='отчество')
    # group - учебная группа
    group = models.ForeignKey(to="StudentGroup", on_delete=models.CASCADE, verbose_name='учебная группа')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'surname', 'patronymic'], name='unique fio student')
        ]
        ordering = ["surname", "name", "patronymic"]
        db_table = "student"

    def __str__(self):
        return self.surname + ' ' + self.name + ' ' + self.patronymic


# модель учебной группы
class StudentGroup(models.Model):
    # номер группы
    number = models.IntegerField(unique=True)
    # специлизация
    specialization = models.CharField(max_length=200)

    class Meta:
        ordering = ['number']
        db_table = "studentGroup"

    def __str__(self):
        return str(self.number)

    def get_absolute_url(self):
        return reverse('group-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('group-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('group-delete', args=[str(self.id)])

    def get_rating_url(self):
        return reverse('rating', args=[str(self.id)])

    def get_study_rating_url(self):
        return reverse('group-study-rating', args=[str(self.id)])

    def get_visiting_rating_url(self):
        return reverse('group-visiting-rating', args=[str(self.id)])

    def get_add_res_rating_url(self):
        return reverse('group-add-res-rating', args=[str(self.id)])

    def get_total_rating(self):
        return reverse('group-total-rating', args=[str(self.id)])



# модель преподавателя
class Teacher(models.Model):
    # имя
    name = models.CharField(max_length=20, verbose_name="Имя")
    # фамилия
    surname = models.CharField(max_length=30, verbose_name="Фамилия")
    # отчество
    patronymic = models.CharField(max_length=30, verbose_name="Отчество")

    def __str__(self):
        return self.surname+" "+self.name

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'surname', 'patronymic'], name='unique fio teacher')
        ]
        ordering = ["surname", "name", "patronymic"]
        db_table = "teacher"

    def get_absolute_url(self):
        return reverse('teacher-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('teacher-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('teacher-delete', args=[str(self.id)])


# модель Дисциплина
class Discipline(models.Model):
    TYPE_EXAM = [
        ('N', ''),
        ('Z', 'зачёт'),
        ('O', 'зачёт с оценкой'),
        ('E', 'экзамен')
    ]

    name = models.CharField(max_length=400, verbose_name="Название", unique=True)
    short_name = models.CharField(max_length=10, verbose_name="Аббревиатура", blank=True)
    teacher = models.ForeignKey(to="Teacher", on_delete=models.CASCADE, verbose_name="Преподаватель", blank=True,
                                null=True)
    course = models.IntegerField(verbose_name="Курс", blank=True, null=True)
    hours = models.IntegerField(verbose_name="Количество часов", blank=True, null=True)

    type_exam = models.CharField(max_length=1, choices=TYPE_EXAM, verbose_name="Тип экзамена")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name'], name='unique name discipline')
        ]
        ordering = ["name"]
        db_table = "discipline"

    def get_absolute_url(self):
        return reverse('discipline-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('discipline-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('discipline-delete', args=[str(self.id)])


# модель оценки
class Mark(models.Model):
    student = models.ForeignKey(to="Student", on_delete=models.CASCADE, verbose_name="Студент")

    discipline = models.ForeignKey(to="GroupDiscipline", on_delete=models.CASCADE, verbose_name="Дисциплина")

    date = models.DateField(verbose_name="Дата")

    ball = models.IntegerField()

    class Meta:
        ordering = ["date", "student"]
        db_table = "mark"


# модель дисциплины группы
class GroupDiscipline(models.Model):
    group = models.ForeignKey(to="StudentGroup", on_delete=models.CASCADE, verbose_name="Взвод")
    discipline = models.ForeignKey(to="Discipline", on_delete=models.CASCADE, verbose_name="Дисциплина")

    class Meta:
        db_table = "groupDiscipline"

system/ejournal/forms.py
from django.forms import ModelForm

from .models import Student


class StudentForm(ModelForm):

    class Meta:
        model = Student
        fields = ("name", "surname",  "patronymic")

system/ejournal/templates/firstapp/discipline_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление дисциплины</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить эту дисциплину "{{ dicsipline.name }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/discipline_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Дисциплина</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>
{% endblock content%}

system/ejournal/templates/firstapp/discipline_detail.html
{% extends 'base.html' %}
{% block content %}
      <h1>Дисциплина</h1>
    <p><strong>Название: </strong><a>{{discipline.name}}</a></p>
    <p><strong>Аббревиатура:</strong><a>{{discipline.short_name}}</a></p>
    <p><strong>Кафедра: </strong><a>{{discipline.departament}}</a></p>
    <p><strong>Преподаватель: </strong><a>{{discipline.teacher}}</a></p>
    <p><strong>Курс: </strong><a>{{discipline.course}}</a></p>
    <p><strong>Часы: </strong><a>{{discipline.hours}}</a></p>
    <p><strong>Тип экзамена: </strong><a>{{discipline.get_type_exam_display}}</a></p>
<button onclick="location.href='{{discipline.get_edit_url}}'">Изменить дисциплину</button>
<button onclick="location.href='{{discipline.get_del_url}}'">Удалить дисциплину</button>
{% endblock %}

system/ejournal/templates/firstapp/discipline_list.html
{% extends 'base.html' %}
<title>Discipline</title>
{% block content %}
  <h1>Список дисциплин</h1>
  <div class="nav-right">
    <a href="{% url 'disсipline-create' %}">Добавить новую дисциплину</a><br>
  </div>
  {% if discipline_list %}
  <ul>
    {% for discipline in discipline_list %}
    {% if discipline.name != "дополнительные обязанности" %}
      <li>
        <a href="{{ discipline.get_absolute_url }}">{{ discipline.name }}</a>
      </li>
    {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Дисциплины отсутствуют</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/group_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление взвода</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить взвод "{{ groupmodel.number }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/group_create.html
{% extends 'base.html' %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="../../../static/scripts/addrow.js"></script>
    <h1>group</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>

{% endblock content %}

system/ejournal/templates/firstapp/group_list.html
{% extends 'base.html' %}
{% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
<title>Учебный группы</title>
{% block content %}
  <h1>Список групп</h1>
  <div class="nav-right">
    <a href="{% url 'group-create' %}">Добавить новую группу</a><br>
  </div>
  {% if groupmodel_list %}
  <ul>
    {% for group in groupmodel_list %}
      <li>
        <a href="{{ group.get_absolute_url }}">{{ group.number }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Отсутствуют группы</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/group_raiting.html
{% extends 'base.html' %}
{% block content %}
<h1>Номер взвода: {{groupmodel.number}}</h1>
<style type="text/css">
    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }
</style>

<p><strong>Кафедра: </strong><a>{{groupmodel.departament}}</a></p>
<p><strong>Специальность: </strong><a>{{groupmodel.specialization}}</a></p>
    <div id="students">
        <div style="margin-left:20px;margin-top:20px">
            <h4>Студенты</h4>
            <table>
                <tbody>
                <tr>
                    {% for title in titles %}
                    <td align="center">{{title}}</td>
                    {% endfor %}
                </tr>
                {% for student in students %}
                <tr>
                    {% for student_data in student %}
                    <td align="center">{{student_data}}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

system/ejournal/templates/firstapp/raiting_log.html
{% extends 'base.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="../../../static/scripts/addrow.js"></script>
<style type="text/css">
    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }
    input[type=date]::-webkit-calendar-picker-indicator {
  opacity: 0;
}
::-webkit-calendar-picker-indicator{
    margin-left: -35px;
}
</style>

<form id="choose_dis" name="discipline">
<select id="discipline" name="choose_discipline">
    {% for discipline in group.groupdiscipline_set.all %}
    {% if discipline.discipline == cur_discipline%}
    <option selected>{{discipline.discipline.name}}</option>
    {% else %}
    <option>{{discipline.discipline.name}}</option>
    {% endif %}
    {% endfor %}
</select>
    <button type="submit">Выбрать дисциплину</button>
</form>

{% if students %}
<button id="addlesson" type="button">Добавить занятие</button>
<form action="" method="post">
{% csrf_token %}
<table id="marks"  name="marks">
    <tr id="hd"><th id="students">Студенты</th>
        {% for date in dates%}
        <th><input type="date" value="{{date}}" name="data"/></th>
        {% endfor %}
    </tr>
    {% for student in stmarks %}
    <tr>
        <td align="center" name="student">{{student.student}}</td>
    {% for j in student.marks %}
    <td align="center"><input value="{{j}}"  name="ocenka" size="2" maxlength="2"/></td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
 <input type="submit" value="Сохранить"/>
</form>

{% endif %}

{% endblock %}

system/ejournal/templates/firstapp/student_info.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Система оценивания студентов ВУЦ</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <style type="text/css">
    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }
</style>

  <body>
    <div>
      <header>
        <div class="nav-left">
          <h1><a href="{% url 'groups' %}">Система оценивания студентов Вуц</a></h1>
        </div>

         <div class="nav-right">
          <a href="{% url 'logout' %}">Выйти из системы</a><br>
         </div>

      </header>
        <h1>Номер взвода: {{group}}</h1>

        <p><strong>Фамилия: </strong><a>{{surname}}</a></p>
        <p><strong>Имя: </strong><a>{{name}}</a></p>
        <p><strong>Отчество: </strong><a>{{patronymic}}</a></p>

        <table>
                <tbody>
                <tr>
                    {% for title in titles %}
                    <td align="center">{{title}}</td>
                    {% endfor %}
                </tr>
                {% for report in reports %}
                <tr>
                    {% for x in report %}
                    <td align="center">{{x}}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

    </div>
  </body>
</html>

system/ejournal/templates/firstapp/teacher_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление преподавателя</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить этого преподователя "{{ teacher }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/teacher_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Преподаватель</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>
{% endblock content%}

system/ejournal/templates/firstapp/teacher_list.html
{% extends 'base.html' %}
{% load static %}
<title>Преподаватели</title>
{% block content %}
  <h1>Список преподавателей</h1>
 <div class="nav-right">
    <a href="{% url 'teacher-create' %}">Добавить нового преподавателя</a><br>
  </div>
  {% if teacher_list %}
  <ul>
    {% for teacher in teacher_list %}
      <li>
        <a href="{{ teacher.get_absolute_url }}">{{ teacher }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Отсутсвуют преподаватели.</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/teacher_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Преподаватель</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />

  </form>

{% endblock content %}